# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 23:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0002_user_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='alias',
            field=models.CharField(default=3, max_length=255),
            preserve_default=False,
        ),
    ]
